---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/ApiNotificationConfiguration.yaml
title: ApiNotificationConfiguration
description: Api Notification Settings
type: object
required:
  - webhook
additionalProperties: true
properties:
  webhook:
    type: string
